In [4]:
import xlwings as xw
import sources.parts_list_0802 as pl
import pandas as pd
import os
from datetime import datetime as dt
import sources.logins as lg
import pathlib
import qrcode
from time import sleep
import xlwings as xw
from IPython.display import Image

from sqlite3 import connect

### TAT time

In [2]:
sn_list = '''
4G391K119
5C730K017
1G366K320
1G403K314
KG391K535
2v644k259
3S101K332
2C728K102
1V696K004
8G403K185
8G361K202
2G391K630
1G402K223
1C741K089
1C643K395
3c309k028
1C643K899
3C309K012


    '''

sn_list = sn_list.strip().split('\n')
len(sn_list)

18

In [5]:
conn = connect('history.db')

In [6]:
#check by sn and record serial
rma_record =[]
for sn in sn_list:
#     sn = 'Jg361K643'
    q = f'''
            SELECT [rma no.],customer_name,model,serial_no,[repair size],approval,[scope connect count],[recieve_date]
            FROM consolidated
            WHERE upper(serial_no) ='{sn.upper()}'

            ORDER BY [rma no.] DESC

        '''
    his_rma = pd.read_sql(q,conn)
    if len(his_rma) > 1:
        display(his_rma)

        try:
            ind = int(input('Select by index[0]: '))
            rma_record.append(his_rma['RMA No.'][0])
            rma_record.append(his_rma['RMA No.'][ind])
        except:
            ind = 0
            rma_record.append(his_rma['RMA No.'][0])
    else:
        rma_record.append(his_rma['RMA No.'][0])
    
    print(rma_record)

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090032,Hanoi Medical University Hospital,EG-600WR,4G391K119,Minor,Approval,4474.0,2023-09-18 13:01:40
1,FMSV2023070063,Hanoi Medical University Hospital,EG-600WR,4G391K119,Minor,Approval,4021.0,2023-07-24 15:41:17
2,FMSV2023040030,Hanoi Medical University Hospital,EG-600WR,4G391K119,Minor,Approval,3479.0,2023-04-11 19:39:42
3,FMSV2022090050,Hanoi Medical University Hospital,EG-600WR,4G391K119,Major,Approval,2677.0,2022-09-22 21:08:54
4,FMSV2020100070,Hanoi Medical University Hospital,EG-600WR,4G391K119,Major,Cancel,2677.0,2020-10-29 13:13:58
5,FMSV2020040024,Hanoi Medical University Hospital,EG-600WR,4G391K119,Minor,Approval,NaN,2020-04-27 17:16:40

Select by index[0]:
['FMSV2023090032']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090040,No. 91 Endoscopy-Gastrointestinal-Gi Scaning T...,EC-760ZP-V/M,5C730K017,Minor,Approval,NaN,2023-09-19 11:22:40
1,FMSV2023080059,No. 91 Endoscopy-Gastrointestinal-GI Scaning T...,EC-760ZP-V/M,5C730K017,Minor,Approval,770.0,2023-08-17 15:47:04

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090045,Minh Duc Hospital,EG-530NW,1G366K320,Minor,Approval,1290.0,2023-09-20 14:28:38
1,FMSV2020120011,MINH DUC HOSPITAL,EG-530NW,1G366K320,Major,Decline,9717.0,2020-12-04 15:41:27
2,FMSV2019110066,MINH DUC HOSPITAL,EG-530NW,1G366K320,Major,Approval,5251.0,2019-11-27 16:41:03
3,FMSV2019040014,MINH DUC HOSPITAL,EG-530NW,1G366K320,Major,Approval,2000.0,2019-04-08 11:26:32

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090050,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Minor,Approval,3762.0,2023-09-21 15:34:17
1,FMSV2020120014,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Major,Approval,1616.0,2020-12-07 16:39:55
2,FMSV2020080030,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Minor,Approval,NaN,2020-08-14 08:33:43
3,FMSV2020060045,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Minor,Approval,NaN,2020-06-17 09:02:11
4,FMSV2020050038,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Minor,Approval,NaN,2020-05-18 17:35:40
5,FMSV2020050026,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Maintain,NoFault,NaN,2020-05-12 16:30:21
6,FMSV2020030056,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Minor,Approval,NaN,2020-03-27 13:29:16
7,FMSV2019020007,"FUJIFILM Vietnam Co., Ltd.",EG-760Z,1G403K314,Minor,Approval,NaN,2019-02-15 20:47:56

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050']
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090055,"FUJIFILM Vietnam Co., Ltd.",VP-7000,2v644k259,Other,Approval,None,2023-09-25 18:32:43
1,FMSV2021110053,"FUJIFILM Vietnam Co., Ltd.",VP-7000,2v644k259,Other,Approval,None,2021-11-15 12:05:02
2,FMSV2021090009,"FUJIFILM Vietnam Co., Ltd.",VP-7000,2v644k259,Other,Approval,None,2021-09-07 17:53:39
3,FMSV2021020003,"FUJIFILM Vietnam Co., Ltd.",VP-7000,2v644k259,Maintain,Approval,None,2021-02-01 08:39:56
4,FMSV2020120056,"FUJIFILM Vietnam Co., Ltd.",VP-7000,2v644k259,Maintain,Approval,None,2020-12-24 13:43:40

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090056,"FUJIFILM Vietnam Co., Ltd.",BL-7000,3S101K332,Other,Approval,None,2023-09-25 18:33:36
1,FMSV2021110052,"FUJIFILM Vietnam Co., Ltd.",BL-7000,3S101K332,Other,Approval,None,2021-11-15 12:04:29
2,FMSV2021090008,"FUJIFILM Vietnam Co., Ltd.",BL-7000,3S101K332,Maintain,Approval,None,2021-09-07 17:52:56
3,FMSV2021020004,"FUJIFILM Vietnam Co., Ltd.",BL-7000,3S101K332,Maintain,Approval,None,2021-02-01 08:40:38
4,FMSV2020120057,"FUJIFILM Vietnam Co., Ltd.",BL-7000,3S101K332,Maintain,Approval,None,2020-12-24 13:44:10

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090057,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Minor,Approval,2046.0,2023-09-25 18:34:50
1,FMSV2022040073,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Minor,Approval,NaN,2022-04-25 19:02:30
2,FMSV2021120070,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Minor,Approval,724.0,2021-12-30 12:40:51
3,FMSV2021110011,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Minor,Approval,NaN,2021-11-03 16:51:02
4,FMSV2021040045,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Major,Approval,NaN,2021-04-15 16:01:41
5,FMSV2021010023,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Minor,Approval,NaN,2021-01-12 15:15:39
6,FMSV2020090017,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Minor,Approval,NaN,2020-09-08 16:51:35
7,FMSV2020060063,FTYO - Loaner Asset,EC-760R-V/I,2C728K102,Maintain,Inspection,NaN,2020-06-23 16:16:33

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090058,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Other,Approval,None,2023-09-26 11:54:42
1,FMSV2023020020,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Other,Inspection,None,2023-02-08 18:41:11
2,FMSV2022100045,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Maintain,Approval,None,2022-10-12 18:36:10
3,FMSV2022030060,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Maintain,Inspection,None,2022-03-31 18:38:43
4,FMSV2021110016,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Other,Approval,None,2021-11-04 12:48:03
5,FMSV2021040033,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Maintain,Inspection,None,2021-04-09 16:48:44
6,FMSV2021010020,"FUJIFILM Vietnam Co., Ltd.",EP-6000,1V696K004,Other,NoFault,None,2021-01-12 15:13:38

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090059,Hung Viet Cancer Hospital,EG-760Z,8G403K185,Major,None,2253.0,2023-09-26 11:58:25
1,FMSV2023080086,Hung Viet Cancer Hospital,EG-760Z,8G403K185,Minor,Approval,NaN,2023-08-22 12:49:07

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090060,Vinh Duc General Hospital,EG-530WR,8G361K202,Major,Approval,NaN,2023-09-26 14:23:37
1,FMSV2021030059,Vinh Duc General Hospital,EG-530WR,8G361K202,Major,Approval,1964.0,2021-03-15 16:24:35

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090061,FTYO - Loaner Asset,EG-600WR,2G391K630,Minor,Approval,NaN,2023-09-27 15:47:56
1,FMSV2023050008,FTYO - Loaner Asset,EG-600WR,2G391K630,Maintain,Inspection,5406.0,2023-05-18 15:10:23
2,FMSV2022100083,FTYO - Loaner Asset,EG-600WR,2G391K630,Maintain,Inspection,NaN,2022-11-02 11:30:03
3,FMSV2022010031,FTYO - Loaner Asset,EG-600WR,2G391K630,Minor,Approval,NaN,2022-01-18 11:19:48
4,FMSV2021040011,FTYO - Loaner Asset,EG-600WR,2G391K630,Major,Approval,NaN,2021-04-05 13:37:15
5,FMSV2020060029,FTYO - Loaner Asset,EG-600WR,2G391K630,Maintain,Inspection,NaN,2020-06-09 14:00:38
6,FMSV2020050015,FTYO - Loaner Asset,EG-600WR,2G391K630,Maintain,Inspection,NaN,2020-05-08 13:12:04
7,FMSV2018010019,FTYO - Loaner Asset,EG-600WR,2G391K630,Major,Transfer,2550.0,2018-01-31 09:18:32

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090066,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,None,4407.0,2023-09-28 16:42:15
1,FMSV2023040026,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,Approval,NaN,2023-04-11 15:21:18
2,FMSV2023010043,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Major,Approval,3087.0,2023-01-31 12:18:38
3,FMSV2022120096,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Other,Approval,NaN,2022-12-26 17:57:59
4,FMSV2022090007,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Major,Approval,2623.0,2022-09-07 15:04:56
5,FMSV2022030038,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Major,Cancel,2623.0,2022-03-18 20:07:53
6,FMSV2021110036,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,NoFault,2517.0,2021-11-09 17:20:05
7,FMSV2021070019,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,Approval,NaN,2021-07-08 16:34:13
8,FMSV2021040091,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,Approval,NaN,2021-04-28 11:19:50
9,FMSV2021010022,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,Approval,NaN,2021-01-12 15:15:06
10,FMSV2020030005,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Major,Approval,1562.0,2020-03-03 09:43:11
11,FMSV2019050024,"FUJIFILM Vietnam Co., Ltd.",EG-760R,1G402K223,Minor,Approval,NaN,2019-05-20 09:01:49

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061', 'FMSV2023090066']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090067,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,None,None,NaN,2023-09-28 16:42:50
1,FMSV2022100038,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Maintain,Approval,NaN,2022-10-12 15:52:09
2,FMSV2022090056,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Minor,Approval,NaN,2022-09-27 16:52:12
3,FMSV2022050046,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Minor,Approval,1151.0,2022-05-20 12:23:30
4,FMSV2022020025,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Maintain,Inspection,NaN,2022-02-22 12:02:42
5,FMSV2021110054,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Minor,Approval,NaN,2021-11-15 12:06:14
6,FMSV2021070021,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Minor,Approval,NaN,2021-07-09 15:25:45
7,FMSV2020120037,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Minor,Approval,700.0,2020-12-17 16:16:31
8,FMSV2020060003,"FUJIFILM Vietnam Co., Ltd.",EC-720R/I,1C741K089,Minor,Approval,NaN,2020-06-01 10:38:26

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061', 'FMSV2023090066', 'FMSV2023090067']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090122,Bac Giang Hospital,EC-530WL3,1C643K395,Major,None,6026.0,2023-09-28 16:58:29
1,FMSV2023040092,Bac Giang Hospital,EC-530WL3,1C643K395,Major,Transfer,6026.0,2023-04-28 19:14:43
2,FMSV2019120020,Bac Giang Hospital,EC-530WL3,1C643K395,Major,Approval,5483.0,2019-12-17 08:11:52
3,FMSV2019060009,Bac Giang Hospital,EC-530WL3,1C643K395,Major,Approval,4645.0,2019-06-05 18:05:33
4,FMSV2016110011,Bac Giang Hospital,EC-530WL3,1C643K395,Minor,Approval,NaN,2016-11-18 14:00:37
5,FMSV2016070003,Bac Giang Hospital,EC-530WL3,1C643K395,Major,Approval,NaN,2016-07-03 00:43:29
6,FMSV2016010008,Bac Giang Hospital,EC-530WL3,1C643K395,Minor,Approval,NaN,2016-01-20 15:09:03

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061', 'FMSV2023090066', 'FMSV2023090067', 'FMSV2023090122']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090125,Thai Nguyen General Hospital,EC-250WL5,3c309k028,Major,None,None,2023-09-28 16:58:57
1,FMSV2023050035,Thai Nguyen General Hospital,EC-250WL5,3c309k028,Major,Transfer,None,2023-05-15 18:29:17
2,FMSV2022030004,Thai Nguyen General Hospital,EC-250WL5,3c309k028,Major,Cancel,None,2022-03-03 12:37:53
3,FMSV2021040060,Thai Nguyen Central General Hospital,EC-250WL5,3c309k028,Minor,Approval,None,2021-04-19 14:21:02
4,FMSV2020060030,Thai Nguyen Central General Hospital,EC-250WL5,3c309k028,Minor,Approval,None,2020-06-10 08:48:33

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061', 'FMSV2023090066', 'FMSV2023090067', 'FMSV2023090122', 'FMSV2023090125']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090127,Bac Giang Hospital,EC-530WL3,1C643K899,Major,None,3373.0,2023-09-28 16:59:16
1,FMSV2023050053,Bac Giang Hospital,EC-530WL3,1C643K899,Major,Transfer,3373.0,2023-05-23 18:21:04
2,FMSV2021030112,Bac Giang Hospital,EC-530WL3,1C643K899,Major,Approval,3250.0,2021-03-31 16:26:16
3,FMSV2020080010,Bac Giang Hospital,EC-530WL3,1C643K899,Major,Decline,3250.0,2020-08-06 08:34:35
4,FMSV2019080069,Bac Giang Hospital,EC-530WL3,1C643K899,Minor,Approval,2679.0,2019-08-16 09:29:06

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061', 'FMSV2023090066', 'FMSV2023090067', 'FMSV2023090122', 'FMSV2023090125', 'FMSV2023090127']

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Repair Size,Approval,Scope Connect Count,RECIEVE_DATE
0,FMSV2023090140,Thai Nguyen General Hospital,EC-250WL5,3C309K012,Minor,Approval,None,2023-09-28 17:01:18
1,FMSV2023050034,Thai Nguyen General Hospital,EC-250WL5,3C309K012,Minor,Transfer,None,2023-05-15 18:28:32
2,FMSV2021070024,Thai Nguyen Central General Hospital,EC-250WL5,3C309K012,Minor,Approval,None,2021-07-13 14:52:24
3,FMSV2020100079,Thai Nguyen Central General Hospital,EC-250WL5,3C309K012,Major,Approval,None,2020-10-30 14:01:36

Select by index[0]:
['FMSV2023090032', 'FMSV2023090040', 'FMSV2023090045', 'FMSV2023090050', 'FMSV2023090053', 'FMSV2023090055', 'FMSV2023090056', 'FMSV2023090057', 'FMSV2023090058', 'FMSV2023090059', 'FMSV2023090060', 'FMSV2023090061', 'FMSV2023090066', 'FMSV2023090067', 'FMSV2023090122', 'FMSV2023090125', 'FMSV2023090127', 'FMSV2023090140']

In [7]:
len(rma_record)

18

In [14]:
rma_list = '''
FMSV2023080081
FMSV2023050040
FMSV2023050052
FMSV2023030014
FMSV2023040072
FMSV2023050014
FMSV2023050022
FMSV2023050031
FMSV2023050032
FMSV2023030051
FMSV2023040071
FMSV2023040076
FMSV2023050003
FMSV2023050019
FMSV2023040059
FMSV2023040073
FMSV2023040074
FMSV2023040075
FMSV2023040080
FMSV2023040081
FMSV2023040082
FMSV2023040083
FMSV2023040084
FMSV2023040085
FMSV2023040086
FMSV2023040087
FMSV2023040088
FMSV2023050005
FMSV2023050009
FMSV2023040042
FMSV2023040031
FMSV2023040001
FMSV2023020033
FMSV2023040062
FMSV2023040061
FMSV2023040056
FMSV2023040055
FMSV2023040050
FMSV2023040028
FMSV2023040003
FMSV2023040053
FMSV2023040052
FMSV2023040037
FMSV2023040035
FMSV2023040022
FMSV2023020064
FMSV2023030055
FMSV2023030072
FMSV2023020030
FMSV2023030062
FMSV2023040011
FMSV2023040012
FMSV2023040026
FMSV2023040054
FMSV2023040030
FMSV2023040044
FMSV2023040047
FMSV2023040051
FMSV2023040023
FMSV2023040009
FMSV2023030056
FMSV2023030015
FMSV2023040029
FMSV2023040016
FMSV2023040014
FMSV2023040013
FMSV2023040008
FMSV2023040007
FMSV2023030077
FMSV2023020009
FMSV2023020007
FMSV2023010021
FMSV2023030076
FMSV2023030080
FMSV2023020015
FMSV2023040018
FMSV2023030074
FMSV2023030066
FMSV2023030065
FMSV2023030063
FMSV2023030057
FMSV2023030047
FMSV2023030045
FMSV2023030028
FMSV2023030025
FMSV2023030024
FMSV2023020055
FMSV2023030004
FMSV2023030071
FMSV2023030064
FMSV2023030059
FMSV2023030038
FMSV2023030037
FMSV2023030029
FMSV2023030027
FMSV2023030026
FMSV2023030023
'''

rma_list = tuple(rma_list.strip().split('\n'))

In [15]:
#combine receive
# rma_list = tuple(rma_record)
q = f'''
        SELECT  DISTINCT c.[rma no.],c.customer_name,c.model,c.serial_no,
        strftime('%Y-%m-%d',CASE 
            WHEN receive NOT NULL THEN receive
            ELSE c.recieve_date END) AS [Receive Date (IN)],
        
        CASE
            WHEN m.quotation IS NULL THEN c.in_inspect_date
            WHEN m.quotation IN ('FOC','WARRANTY') THEN c.in_inspect_date
            ELSE m.quotation  END as [Quoted Date],
        
        confirmation AS [PO rec. Date],
        m.part_order_date as [Part Order Date],
        CASE
            WHEN m.part_received_date NOT NULL THEN m.part_received_date
            ELSE c.[Part Select Date] END AS [Part Receive Date],
        ROUND(JULIANDAY(m.note) - JULIANDAY(c.[Part Select Date])) AS [TAT Parts],
        
        CASE 
            WHEN m.start_repair NOT NULL THEN m.start_repair
            ELSE strftime('%Y-%m-%d',re.[Start Time]) END AS[Repair Start Date],
        ROUND(JULIANDAY(c.qc) - JULIANDAY(re.[Start Time])) AS [TAT Repair],
        CASE
            WHEN m.qc_date NOT NULL THEN m.qc_date
            ELSE strftime('%Y-%m-%d',c.qc) END AS [Ship Date (OUT)],
        
        ROUND(JULIANDAY(c.qc) - JULIANDAY(receive)) AS [TAT Days Completed]
        
        FROM (consolidated c
        LEFT JOIN repair_code re ON c.[RMA NO.] = re.[RMA NO.])
        LEFT JOIN new_ml m ON c.[RMA NO.] = m.rma
        WHERE c.[rma no.] IN {rma_list}
        
        ORDER BY c.[rma no.]
        
    '''

tat_repair = pd.read_sql(q,conn)
tat_repair.head()#.to_excel('inspection\\tat_repair.xlsx',index=False)

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Receive Date (IN),Quoted Date,PO rec. Date,Part Order Date,Part Receive Date,TAT Parts,Repair Start Date,TAT Repair,Ship Date (OUT),TAT Days Completed
0,FMSV2023010021,"FUJIFILM Vietnam Co., Ltd.",VP-3500,1V609K145,2023-01-10,2023-01-10 17:03:08,None,None,2023-04-12 10:24:15,None,2023-04-12,8.0,2023-04-20,None
1,FMSV2023020007,FTYO - Loaner Asset,XL-4450,1S094K195,2023-02-02,2023-02-10 12:55:31,None,None,2023-04-10 17:41:30,None,2023-04-10,8.0,2023-04-18,None
2,FMSV2023020009,FTYO - Loaner Asset,XL-4450,1S094K192,2023-02-02,2023-02-13 12:28:57,None,None,2023-04-10 16:31:43,None,2023-04-10,8.0,2023-04-18,None
3,FMSV2023020015,Tam Anh General Hospital,EC-760ZP-V/L,6C731K062,2023-02-07,2023-02-07 15:38:55,None,None,2023-04-05 13:04:28,None,2023-04-05,6.0,2023-04-11,None
4,FMSV2023020030,"FUJIFILM Vietnam Co., Ltd.",EC-530WI3,1C642K350,2023-02-13,2023-02-21 17:19:46,None,None,2023-04-13 12:35:48,None,2023-04-13,7.0,2023-04-20,None

In [17]:
for i in range(len(tat_repair)):
    if tat_repair['Quoted Date'][i]== None:
        tat_repair['Quoted Date'][i] = tat_repair['Receive Date (IN)'][i]
    if tat_repair['PO rec. Date'][i]== None:
        tat_repair['PO rec. Date'][i] = tat_repair['Quoted Date'][i]
    if tat_repair['Part Order Date'][i]== None:
        tat_repair['Part Order Date'][i] = tat_repair['PO rec. Date'][i]
    if tat_repair['Part Receive Date'][i]== None:
        tat_repair['Part Receive Date'][i] = tat_repair['Part Order Date'][i]
    if tat_repair['Repair Start Date'][i]== None:
        tat_repair['Repair Start Date'][i] = tat_repair['Part Receive Date'][i]
    if tat_repair['Ship Date (OUT)'][i]== None:
        tat_repair['Ship Date (OUT)'][i] = tat_repair['Repair Start Date'][i]
tat_repair

,RMA No.,CUSTOMER_NAME,MODEL,SERIAL_NO,Receive Date (IN),Quoted Date,PO rec. Date,Part Order Date,Part Receive Date,TAT Parts,Repair Start Date,TAT Repair,Ship Date (OUT),TAT Days Completed
0,FMSV2023010021,"FUJIFILM Vietnam Co., Ltd.",VP-3500,1V609K145,2023-01-10,2023-01-10 17:03:08,2023-01-10 17:03:08,2023-01-10 17:03:08,2023-04-12 10:24:15,None,2023-04-12,8.0,2023-04-20,None
1,FMSV2023020007,FTYO - Loaner Asset,XL-4450,1S094K195,2023-02-02,2023-02-10 12:55:31,2023-02-10 12:55:31,2023-02-10 12:55:31,2023-04-10 17:41:30,None,2023-04-10,8.0,2023-04-18,None
2,FMSV2023020009,FTYO - Loaner Asset,XL-4450,1S094K192,2023-02-02,2023-02-13 12:28:57,2023-02-13 12:28:57,2023-02-13 12:28:57,2023-04-10 16:31:43,None,2023-04-10,8.0,2023-04-18,None
3,FMSV2023020015,Tam Anh General Hospital,EC-760ZP-V/L,6C731K062,2023-02-07,2023-02-07 15:38:55,2023-02-07 15:38:55,2023-02-07 15:38:55,2023-04-05 13:04:28,None,2023-04-05,6.0,2023-04-11,None
4,FMSV2023020030,"FUJIFILM Vietnam Co., Ltd.",EC-530WI3,1C642K350,2023-02-13,2023-02-21 17:19:46,2023-02-21 17:19:46,2023-02-21 17:19:46,2023-04-13 12:35:48,None,2023-04-13,7.0,2023-04-20,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,FMSV2023050031,Phu Tho General Hospital,EC-530WL3,JC643K007,2023-05-12,2023-05-17 18:12:18,2023-05-17 18:12:18,2023-05-17 18:12:18,2023-05-17 18:12:27,None,2023-05-17,2.0,2023-05-19,None
93,FMSV2023050032,Phu Tho General Hospital,EG-530WR,JG361K643,2023-05-12,2023-05-17 18:22:10,2023-05-17 18:22:10,2023-05-17 18:22:10,2023-05-17 18:22:18,None,2023-05-17,2.0,2023-05-19,None
94,FMSV2023050040,Hoang Long Clinic,EG-580UR,1U048K096,2023-05-17,2023-05-24 15:56:45,2023-05-24 15:56:45,2023-05-24 15:56:45,2023-05-24 15:56:51,None,2023-05-24,2.0,2023-05-26,None
95,FMSV2023050052,Hue University of Medicine and Pharmacy - Ginec,EC-530WI3,2C642D166,2023-05-24,2023-05-24 12:51:34,2023-05-24 12:51:34,2023-05-24 12:51:34,2023-05-24 12:51:41,None,2023-05-24,0.0,2023-05-24,None
96,FMSV2023080081,FTYO - Loaner Asset,XL-4450,1S094K191,2023-08-21,2023-08-25 17:16:07,2023-08-25 17:16:07,2023-08-25 17:16:07,2023-09-18 17:17:46,None,2023-09-18 17:17:46,NaN,2023-09-18 17:17:46,None

In [18]:
tat_repair.to_excel('inspection\\tat_repair.xlsx',index=False)
xw.Book('inspection\\tat_repair.xlsx')

In [ ]:
pd.read_sql('select WORKINGDAY(strptime("2023-05-15","%Y-%m-%d"),strptime("2023-05-28","%Y-%m-%d"))',conn)

In [ ]:
q = f'''
        SELECT DISTINCT re.[rma no.],re.[Start Time],
        (re.[End Time]-re.[Start Time]) as [TAT Repair],re.[End Time]
        
        FROM repair_code re
        WHERE re.[rma no.] IN {tuple(rma_list)}
    '''
pd.read_sql(q,conn).to_excel('inspection\\tat_repair.xlsx')

### HCAP KICK-OFF

In [ ]:

q = '''SELECT * 
        
        FROM transfers
        WHERE return IS  NULL
        AND customer NOT LIKE '%FUJIFILM%'

    '''

pd.read_sql(q,conn)
# 181 items

In [ ]:
# amount of waiting confirm
q = '''SELECT COUNT(*),SUM(price) AS [Amount of Waiting confirm($)]
        FROM m_list
        WHERE status LIKE '%waiting confirm'
    '''
pd.read_sql(q,conn)

In [ ]:
# total price
q = '''
        SELECT COUNT(*),SUM(part_list_date) AS [Amount of Transfers($)]
        FROM transfers
        WHERE return is null
        AND customer NOT LIKE '%FUJIFILM%'
    '''
pd.read_sql(q,conn)

In [ ]:
# min receive
q = '''SELECT MIN(RECEIVE)
        from transfers
        WHERE return is null
        AND part_list_date not null
        '''
pd.read_sql(q,conn)

In [ ]:
# GROUP BY CUSTOMER
q = '''
        SELECT customer,round(sum(part_list_date),0) AS [Price($)]
        FROM TRANSFERS
        WHERE return is null
        AND part_list_date NOT NULL
        AND customer NOT LIKE '%FUJIFILM%'
        
        group by customer
        HAVING [price($)] >10000
        ORDER BY [price($)] DESC
    '''
pd.read_sql(q,conn)

In [ ]:
#count BY customer
q = '''SELECT customer,round(sum(part_list_date),0) AS [Price($)], count(*) AS [count]
        
        FROM transfers
        
        WHERE return is null
        AND part_list_date NOT NULL
        AND customer NOT LIKE '%FUJIFILM%'
        
        GROUP BY customer
        HAVING [count] >=3
        ORDER BY [Price($)] DESC,[count] DESC
        

'''

pd.read_sql(q,conn)

### Bach Mai

In [ ]:
customer_name = 'Bach Mai Hospital'
q = f'''SELECT model,count(*) As [Quantity], round(sum(part_list_date)) AS [Amount($)]
        FROM transfers
        
        WHERE return is null
        
        AND part_list_date NOT NULL
        AND customer = '{customer_name}'
        
        GROUP BY model
        ORDER BY [Amount($)] DESC
        
    
    '''
pd.read_sql(q,conn)

In [ ]:
model ='EG-600WR'

q = f'''SELECT rma,tf.model,sn,strftime("%d-%m-%Y",receive) as received,
                strftime("%Y",[date installed]) as[Year Installed],

                issue,round(part_list_date) AS [Dealer Price (GP 41%)],
                round(part_list_date*0.85) AS [GP 20%]
        
        FROM transfers tf
        LEFT JOIN install ins ON tf.sn = ins.[serial no.]
        
        WHERE return is null
        AND part_list_date NOT NULL
        AND customer = '{customer_name}'
        and tf.model = '{model}'
        ORDER BY [Year Installed] DESC, [Dealer Price (GP 41%)] DESC
    '''
print(f'{customer_name.upper()} - Model: {model}')
pd.read_sql(q,conn)

In [ ]:
model ='EC-600WI'

q = f'''SELECT rma,tf.model,sn,strftime("%d-%m-%Y",receive) as received,
                strftime("%Y",[date installed]) as[Year Installed],

                issue,round(part_list_date) - round(part_list_date*0.85) AS [GP 20%]
        
        FROM transfers tf
        LEFT JOIN install ins ON tf.sn = ins.[serial no.]
        
        WHERE return is null
        AND part_list_date NOT NULL
        AND customer = '{customer_name}'
        and tf.model = '{model}'
        ORDER BY [Year Installed] DESC, [GP 20%] DESC
    '''
print(f'{customer_name.upper()} - Model: {model}')
pd.read_sql(q,conn)