In [1]:
import pandas as pd
from sqlite3 import connect

conn = connect('bachmai.db')

In [10]:
q = '''
        SELECT DISTINCT model,count(*) AS QTY
        
        
        
        FROM install
        WHERE [customer code] = 'FMSV00038'
        GROUP BY model
        
        ORDER BY QTY DESC
        
    '''
pd.read_sql(q,conn)

             Model  QTY
0         EG-600WR  106
1         EC-600WI   57
2         EG-590WR   13
3             JW-2   11
4          EP-6000   10
5        EC-720R/I    9
6   CDL1909A(230V)    8
7         EG-530WR    7
8      EG-600WR V2    6
9   PC-410(230V D)    5
10        ED-580XT    4
11       EC-590WL4    4
12        EC-530WI    4
13         XL-4450    3
14       VP-4450HD    3
15       EG-580NW2    3
16        EN-450T5    2
17        EG-530NW    2
18        EC-590WI    2
19       EC-530WL3    2
20         VP-7000    1
21         SU-8000    1
22           PB-20    1
23          GW-100    1
24         EG-720R    1
25        EG-590ZW    1
26        EG-580UT    1
27        EG-580UR    1
28       EG-530UR2    1
29        ED-530XT    1
30        EC-600WL    1
31         BL-7000    1

In [17]:
q = '''
        SELECT DISTINCT model,
        strftime('%Y',[date installed]) as YEAR, COUNT(*)
        
        
        
        FROM install
        WHERE [customer code] = 'FMSV00038'
        GROUP BY model, YEAR
        
       
        
    '''
details = pd.read_sql(q,conn)

In [18]:
details.to_excel('details.xlsx',index = False)